apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ingress.yaml") . | sha256sum }}
      labels: {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- $pullSecrets := concat (default list .Values.global.imagePullSecrets) (default list .Values.imagePullSecrets) -}}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- range $pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: BACKEND_URL
              value: {{ .Values.backendUrl | quote }}
