apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- $pullSecrets := concat (default list .Values.global.imagePullSecrets) (default list .Values.imagePullSecrets) -}}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- range $pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: DB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: JWT_EXPIRATION_MS
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: DB_USERNAME

            - name: DB_PASSWORD   
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secrets
                  key: DB_PASSWORD
