apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
